#!/bin/bash
name=$(basename $0)

dir=$(basename $(pwd))
if [[ "${dir}" != "app_rwmem" ]]; then
	echo "${name}: expect you run the test cases script from the app_rwmem directory"
	exit 1
fi

PASS_STR="---Test PASSED---"
DRV_LOC=../drv_rwmem
DRV=devmem_rw


failit()
{
	echo "*FAIL*"
	exit 1
}

pio_test()
{
echo "================= IO port (PIO) Test ========================="
PIO=sample_keybd_read
if [[ -f ./${PIO} ]] ; then
    echo "Running script \"${PIO} -t\" now, pl wait ..."
	./${PIO} -t >/dev/null   # run the script as a testcase, 3 iterations only
	if [[ $? -ne 0 ]] ; then
		failit
	else
		echo "${PASS_STR}"
	fi
else
	echo "Script ${PIO} not present? aborting..."
	exit 1
fi
}

prep_devmem_drv()
{
(
cd ${DRV_LOC}
echo "
$(basename $(pwd)): Building driver module..."
make >/dev/null 2>&1 || failit
sudo rmmod ${DRV} 2>/dev/null
sudo dmesg -C
sudo insmod ${DRV}.ko || failit
lsmod |grep -w ${DRV}
)
# back in 'app_rwmem' dir now
echo "$(pwd): Building..."
make >/dev/null 2>&1 || failit
echo "Turn OFF usermode ASLR"
sudo sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"
}

userspace_ram_rdwr_test()
{
local WRMEM_DBG=./wrmem_dbg
local BYTES2WRITE=0x112233ee
local EXPECT2READ="ee 33 22 11"

echo
echo "================= Userspace RAM memory rd/wr Test ========================="
prep_devmem_drv

uva=$(sudo ${WRMEM_DBG} 2>/dev/null |grep "gbuf @" |awk '{print $3}')
[[ -z "${uva}" ]] && {
	echo "${WRMEM_DBG} failed to obtain sample debug UVA? aborting..."
	failit
}
echo "uva=${uva}"

echo "sudo ${WRMEM_DBG} ${uva} ${BYTES2WRITE} > tmp 2>/dev/null"
sudo ${WRMEM_DBG} ${uva} ${BYTES2WRITE} > tmp 2>/dev/null || failit
grep "^00000000 ${EXPECT2READ}" tmp >/dev/null 2>&1
[[ $? -ne 0 ]] && failit || echo "${PASS_STR}"
rm -f tmp

echo "Restore usermode ASLR setting"
sudo sh -c "echo ${ASLR} > /proc/sys/kernel/randomize_va_space"
}

PROCMAP=procmap
kernelspace_ram_rd_test()
{
echo
hash ${PROCMAP} 2>/dev/null || {
	echo "${name}: expect to have the *procmap* utility project installed and in the PATH"
	echo "URL: https://github.com/kaiwan/procmap"
	echo "First pl install it and set the PATH, then rerun this script."
	failit
}
echo "================= Kernel-space RAM memory read Test ========================="

echo "Running ${PROCMAP} now to obtain the kernel's PAGE_OFFSET value:
${PROCMAP} --pid=1 --only-kernel --verbose |grep "^PAGE_OFFSET" |awk '{print $3}'"
PGOFF=$(${PROCMAP} --pid=1 --only-kernel --verbose |grep "^PAGE_OFFSET" |awk '{print $3}') || failit
echo "PAGE_OFFSET via ${PROCMAP}: ${PGOFF}"
prep_devmem_drv

local RAMFILE=/tmp/ram_first16M.txt
local SIZE2READ=$((16*1024*1024))   # 16M, the max
echo "
Using devmem_rw to read the first 16MB of RAM now into the file ${RAMFILE}... patience ...
sudo ./rdmem ${PGOFF} ${SIZE2READ} > ${RAMFILE}"
sudo ./rdmem ${PGOFF} ${SIZE2READ} > ${RAMFILE} || failit && echo "${PASS_STR}"

echo "
To see possibly interesting portions of first 16MB RAM, run this cmd:
egrep -v \
\"00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff\" \
${RAMFILE}"
#rm -f ${RAMFILE}

echo "Restore usermode ASLR setting"
sudo sh -c "echo ${ASLR} > /proc/sys/kernel/randomize_va_space"
}


#--- 'main'
ASLR=$(cat /proc/sys/kernel/randomize_va_space)

pio_test
#userspace_ram_rdwr_test
kernelspace_ram_rd_test

exit 0
